---
apiVersion: v1
kind: Namespace
metadata:
  name: golf-event-centre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: golf-event-centre
    app.kubernetes.io/name: golf-event-centre
  annotations:
    polaris.fairwinds.com/notReadOnlyRootFilesystem-exempt: 'true'
  name: golf-event-centre
  namespace: golf-event-centre
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: golf-event-centre
      app.kubernetes.io/name: golf-event-centre
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: golf-event-centre
        app.kubernetes.io/name: golf-event-centre
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
      - env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: userKey
              name: golf-event-centre-login
        - name: ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: passwordKey
              name: golf-event-centre-login
        image: golf-event-centre/golf-event-centre:latest
        imagePullPolicy: Always
        name: golf-event-centre
        ports:
        - containerPort: 3000
          name: golf-event-centre
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: golf-event-centre
    app.kubernetes.io/name: golf-event-centre
  name: golf-event-centre
  namespace: golf-event-centre
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: golf-event-centre
    app.kubernetes.io/name: golf-event-centre

